name: Build website

on:
  pull_request:
    branches:
      - master
    paths:
      - website/**
      - '!website/README.md'
  workflow_dispatch:

jobs:
  build:
    name: Build website

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
        working-directory: website

      - name: Build website
        run: yarn build
        working-directory: website
