name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - website/**
      - '!website/README.md'
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
        working-directory: website

      - name: Build
        run: yarn build
        working-directory: website

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: website/build

  deploy:
    name: Deploy to GitHub Pages

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
